import keyMirror from "keymirror";

export default keyMirror({
    VIEW_ACTION: null,
    SERVER_ACTION: null,
    ROUTER_ACTION: null,
    //app
    MODAL_STATUS: null,
    //user
    USER_STATUS: null,
    USER_LOGINOUT: null,
    USER_REGISTER: null,
    USER_FORGET: null,
    USER_DATA_ALL: null,
    USER_DATA_ONE: null,
    USER_ADD: null,
    USER_EDIT: null,
    //company
    COMPANY_DATA_ALL: null,
    COMPANY_DATA_ONE: null,
    COMPANY_DATA_SORT: null,
    COMPANY_DATA_PAGE: null,
    COMPANY_DATA_FILTER: null,
    COMPANY_ADD: null,
    COMPANY_EDIT: null,
    COMPANY_CHECKBOX: null,
    //client
    CLIENT_DATA_ALL: null,
    CLIENT_DATA_ONE: null,
    CLIENT_DATA_SORT: null,
    CLIENT_DATA_PAGE: null,
    CLIENT_DATA_FILTER: null,
    CLIENT_ADD: null,
    CLIENT_EDIT: null,
    CLIENT_CHECKBOX: null,
    //tag
    TAG_GROUP_DATA_ALL: null,
    TAG_GROUP_DATA_ONE: null,
    TAG_GROUP_DATA_SORT: null,
    TAG_GROUP_DATA_PAGE: null,
    TAG_GROUP_DATA_FILTER: null,
    TAG_GROUP_CHECKBOX: null,
    TAG_ITEM_DATA_ALL: null,
    TAG_ITEM_DATA_ONE: null,
    TAG_ITEM_DATA_SORT: null,
    TAG_ITEM_DATA_PAGE: null,
    TAG_ITEM_DATA_FILTER: null,
    TAG_ITEM_CHECKBOX: null,
    TAG_INDUSTRY_DATA_ALL: null,
    TAG_INDUSTRY_DATA_ONE: null,
    TAG_INDUSTRY_DATA_SORT: null,
    TAG_INDUSTRY_DATA_PAGE: null,
    TAG_INDUSTRY_DATA_FILTER: null,
    TAG_INDUSTRY_CHECKBOX: null,
    TAG_CAREER_DATA_ALL: null,
    TAG_CAREER_DATA_ONE: null,
    TAG_CAREER_DATA_SORT: null,
    TAG_CAREER_DATA_PAGE: null,
    TAG_CAREER_DATA_FILTER: null,
    TAG_CAREER_CHECKBOX: null,
    TAG_DATA_ALL: null,
    TAG_ADD: null,
    TAG_EDIT: null,
    TAG_PANEL: null,
});
